import os
from datetime import datetime

CODE_DIR = os.path.dirname(os.path.abspath(__file__))
DOCS_DIR = os.path.join(CODE_DIR, '..', 'docs')

def load_system_prompt():
    with open(os.path.join(CODE_DIR, 'SYSTEM_PROMPT.md'), 'r', encoding='utf-8') as f:
        return f.read()


def get_current_timestamp(file_fmt: bool = False) -> str:
    if file_fmt:
        return datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return datetime.now().strftime("%d %B %Y %H:%M:%S")


def create_new_observations_post(content: str, model_name: str):
    title = f"Observations_{get_current_timestamp(file_fmt=True)}"
    with open(os.path.join(DOCS_DIR, 'posts', f'{title}.md'), 'w', encoding='utf-8') as f:
        f.write(content + f"\n\n*Generated by {model_name}*")


def read_memory_file(file_path: str = os.path.join(CODE_DIR, 'memory.md')) -> str:
    with open(file_path, 'r', encoding='utf-8') as f:
        return f.read()
    

def write_memory_file(content: str, file_path: str = os.path.join(CODE_DIR, 'memory.md')):
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
