import os
from datetime import datetime
from src.state import CURRENT_RUN_ID_MEMORY, CURRENT_RUN_ID_POST

CODE_DIR = os.path.dirname(os.path.abspath(__file__))
DOCS_DIR = os.path.join(CODE_DIR, '..', 'docs')

def load_system_prompt():
    with open(os.path.join(CODE_DIR, 'SYSTEM_PROMPT.md'), 'r', encoding='utf-8') as f:
        return f.read()


def get_current_timestamp(file_fmt: bool = False) -> str:
    if file_fmt:
        return datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    return datetime.now().strftime("%d %B %Y %H:%M:%S")


def create_new_observations_post(content: str, model_name: str, run_id: str = None):
    if run_id:
        global CURRENT_RUN_ID_POST
        if not CURRENT_RUN_ID_POST:
            CURRENT_RUN_ID_POST = run_id
        else:
            raise RuntimeError('A blog post has already been created for this run, cannot create another one.')
    title = f"Observations_{get_current_timestamp(file_fmt=True)}"
    with open(os.path.join(DOCS_DIR, 'posts', f'{title}.md'), 'w', encoding='utf-8') as f:
        f.write(content + f"\n\n*Generated by {model_name}*")


def read_memory_file() -> str:
    file_path = os.path.join(CODE_DIR, 'memory.md')
    with open(file_path, 'r', encoding='utf-8') as f:
        return f.read()
    

def write_memory_file(content: str, run_id: str = ''):
    file_path = os.path.join(CODE_DIR, 'memory.md')
    if run_id:
        global CURRENT_RUN_ID_MEMORY
        if not CURRENT_RUN_ID_MEMORY:
            CURRENT_RUN_ID_MEMORY = run_id
        else:
            raise RuntimeError('A memory has already been written for this run, cannot overwrite it again.')
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
